# Generated by Django 5.1.2 on 2025-03-18 11:59

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2XL'), ('XXXL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL'), ('Free Size', 'Free Size'), ('EU 36', 'EU 36'), ('EU 37', 'EU 37'), ('EU 38', 'EU 38'), ('EU 39', 'EU 39'), ('EU 40', 'EU 40'), ('EU 41', 'EU 41'), ('EU 42', 'EU 42'), ('EU 43', 'EU 43'), ('EU 44', 'EU 44'), ('EU 45', 'EU 45'), ('EU 46', 'EU 46'), ('US 6', 'US 6'), ('US 7', 'US 7'), ('US 8', 'US 8'), ('US 9', 'US 9'), ('US 10', 'US 10'), ('US 11', 'US 11'), ('US 12', 'US 12'), ('0-3M', '0-3 Months'), ('3-6M', '3-6 Months'), ('6-12M', '6-12 Months'), ('1-2Y', '1-2 Years'), ('2-3Y', '2-3 Years'), ('3-4Y', '3-4 Years'), ('4-5Y', '4-5 Years'), ('5-6Y', '5-6 Years'), ('6-7Y', '6-7 Years'), ('7-8Y', '7-8 Years'), ('8-9Y', '8-9 Years'), ('9-10Y', '9-10 Years'), ('Custom', 'Custom (Specify in Description)')], default='', max_length=200),
        ),
    ]
