# Generated by Django 5.1.2 on 2025-07-10 20:30

# import cloudinary_storage.storage  # Disabled for local testing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/'),  # Changed to local storage
        ),
    ]
