# Generated by Django 5.1.2 on 2026-04-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='shop',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='shops/banners/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='instagram',
            field=models.CharField(blank=True, help_text='Instagram handle without @', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shops/logos/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number including country code', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
