# Generated by Django 5.1.2 on 2026-04-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_order_buyer_remove_order_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='layout_mode',
            field=models.CharField(choices=[('all', 'All Products'), ('categories', 'By Category')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='sort_order',
            field=models.CharField(choices=[('newest', 'Newest First'), ('price_asc', 'Price: Low to High'), ('price_desc', 'Price: High to Low')], default='newest', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='store_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Temporarily Closed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='store_status_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='tagline',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
