# Generated by Django 5.1.2 on 2026-04-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_shop_premium_storetextblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='paystack_email_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='paystack_subscription_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='store_video_file',
            field=models.FileField(blank=True, help_text='Uploaded video file', null=True, upload_to='store_videos/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='store_video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL for the store promo video', null=True),
        ),
    ]
