# Generated by Django 5.1.2 on 2026-05-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_shop_video_file_and_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, help_text='Set when subscription is cancelled — premium access continues until this date', null=True),
        ),
    ]
