# Generated by Django 5.1.2 on 2026-05-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_shop_premium_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='paystack_authorization_code',
            field=models.CharField(blank=True, help_text='Card authorization code — used to create a subscription without a new payment', max_length=200, null=True),
        ),
    ]
