# Generated by Django 5.1.2 on 2026-05-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_block_style_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='shop',
            name='banner_color',
            field=models.CharField(blank=True, help_text='Solid or gradient color used as banner when no image is uploaded', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, default='', help_text='Comma-separated sizes stored here for indexing; authoritative data is in variants'),
        ),
    ]
