# Generated by Django 5.1.2 on 2026-04-19 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('growth', 'Growth'), ('pro', 'Pro')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_products', models.PositiveIntegerField(default=10)),
                ('promoted_listings', models.BooleanField(default=False)),
                ('priority_search', models.BooleanField(default=False)),
                ('verified_badge', models.BooleanField(default=False)),
                ('featured_on_homepage', models.BooleanField(default=False)),
                ('social_promotion', models.BooleanField(default=False)),
                ('analytics_access', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan')),
            ],
        ),
    ]
