# Generated by Django 5.1.2 on 2025-12-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfitbundle',
            name='theme',
            field=models.CharField(choices=[('office_chic', 'Office Chic'), ('casual_friday', 'Casual Friday'), ('date_night', 'Date Night'), ('weekend_vibes', 'Weekend Vibes'), ('athleisure', 'Athleisure'), ('brunch_ready', 'Brunch Ready'), ('night_out', 'Night Out'), ('business_casual', 'Business Casual'), ('street_style', 'Street Style'), ('beach_day', 'Beach Day'), ('gym_workout', 'Gym Workout'), ('yoga_session', 'Yoga Session'), ('running_gear', 'Running Gear'), ('training_essentials', 'Training Essentials'), ('fitness_focus', 'Fitness Focus'), ('cardio_ready', 'Cardio Ready'), ('strength_training', 'Strength Training'), ('active_recovery', 'Active Recovery')], help_text='Style theme for this outfit', max_length=50),
        ),
    ]
